# Generated by Django 5.1.5 on 2025-02-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_delete_profile'),
        ('users', '0002_profile'),
    ]

    operations = [
    ]
